### ISSUE TITLE
qbcore?

### ISSUE THREAD

**Issue by ghost** [CsokiHUN/esx_briefcase#1]
Make pls Qbcore!

**Comment by CsokiHUN** [comment]
Hi!
i tried blind write qbcore script (i dont have qbcore devserver 😄), but not sure working fine. Please check script in your server.
I created new branch for qb script: [url](https://github.com/CsokiHUN/fivem_briefcase/tree/qbcore)

**Comment by ghost** [comment]
Ill try that right away!

**Comment by ghost** [comment]
do i need a item?

**Comment by CsokiHUN** [comment]
> do i need a item?

no, the script checks your money

**Comment by ghost** [comment]
ah ok
